//------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by a tool
//	Changes will be lost if code is regenerated
// </auto-generated>
//------------------------------------------------------------------------------
#ifndef __SPARK_RENDERER_SHADER_GLSL_FOR_GLES3_FEATURE_LEVEL_GLSLES30_DEFAULTSHADER_HPP_INCLUDED__
#define __SPARK_RENDERER_SHADER_GLSL_FOR_GLES3_FEATURE_LEVEL_GLSLES30_DEFAULTSHADER_HPP_INCLUDED__

namespace spark {
	namespace renderer {
		namespace shader {
			namespace glsl_for_gles3_feature_level_glsles30 {
				/// <summary>
				///
				/// <summary>
				class DefaultShader
				{
				public:
					/// <summary>
					///
					/// <summary>
					DefaultShader(void)
					{
					}

					/// <summary>
					///
					/// <summary>
					virtual ~DefaultShader(void)
					{
					}

				public:
					/// <summary>
					///
					/// <summary>
					const char* GetVertexShader() const
					{
						const char* vertexShaderStr =
							"#version 300 es\n"
							"precision mediump float;\n"
							"\n"
							"// Input\n"
							"in vec3 aVertexPosition;\n"
							"in vec3 aVertexNormal;\n"
							"in vec4 aVertexColor;\n"
							"in vec2 aTextureCoord;\n"
							"in vec3 aBarycentric;\n"
							"\n"
							"uniform mat4 uModelViewProjectionMatrix;\n"
							"uniform mat4 uModelViewMatrix;\n"
							"uniform mat4 uModelMatrix;\n"
							"uniform mat3 uNormalMatrix;\n"
							"\n"
							"// Varying\n"
							"out vec4 color;\n"
							"out vec3 vertexNormal;\n"
							"out vec2 textureCoord;\n"
							"out vec3 barycentric;\n"
							"\n"
							"out vec3 fragPosition;\n"
							"\n"
							"const float POINT_SIZE = 3.0;\n"
							"\n"
							"//--------------------------------------------------------------------------------------\n"
							"//\n"
							"//--------------------------------------------------------------------------------------\n"
							"void main()\n"
							"{    \n"
							"    color = aVertexColor;\n"
							"    vertexNormal = normalize(uNormalMatrix * aVertexNormal);;\n"
							"    textureCoord = aTextureCoord;\n"
							"    barycentric = aBarycentric;\n"
							"        \n"
							"    vec4 worldPos = uModelMatrix * vec4(aVertexPosition, 1.0);\n"
							"    fragPosition = worldPos.xyz;\n"
							"    gl_Position = uModelViewProjectionMatrix * vec4(aVertexPosition, 1.0);\n"
							"    gl_PointSize = POINT_SIZE;\n"
							"}\n"
							"\n"
							"\n"
							;
						return vertexShaderStr;
					}

					/// <summary>
					///
					/// <summary>
					const char* GetFragmentShader() const
					{
						const char* fragmentShaderStr =
							"#version 300 es\n"
							"precision mediump float;\n"
							"\n"
							"// Varying\n"
							"in vec4 color;\n"
							"in vec3 vertexNormal;\n"
							"in vec2 textureCoord;\n"
							"in vec3 barycentric;\n"
							"in vec3 fragPosition;\n"
							"\n"
							"// Input\n"
							"uniform sampler2D uTexture0;\n"
							"uniform int uDrawMode;\n"
							"uniform vec3 uFontColor;\n"
							"\n"
							"// Light\n"
							"uniform int uDirectionalLightCount;\n"
							"uniform vec3 uDirectionalLightDirection[4];\n"
							"uniform vec3 uDirectionalLightColor[4];\n"
							"uniform float uDirectionalLightIntensity[4];\n"
							"\n"
							"uniform int uPointLightCount;\n"
							"uniform vec3 uPointLightPosition[4];\n"
							"uniform vec3 uPointLightColor[4];\n"
							"uniform float uPointLightIntensity[4];\n"
							"uniform float uPointLightRange[4];\n"
							"\n"
							"// PBR\n"
							"uniform vec3 uAlbedo;\n"
							"uniform float uRoughness;\n"
							"uniform float uMetallic;\n"
							"\n"
							"// Out\n"
							"out vec4 fragColor;\n"
							"\n"
							"#define MAX_LIGHTS 16\n"
							"\n"
							"//--------------------------------------------------------------------------------------\n"
							"// uDrawMode (uniform) sets the draw mode for this draw call.\n"
							"//--------------------------------------------------------------------------------------\n"
							"const int DRAW_TEXTURE     = 1; // DrawMode = 1: Used to draw texture\n"
							"const int DRAW_FONT        = 2; // DrawMode = 2: Used to draw glyphs\n"
							"const int DRAW_NORMALS     = 3; // DrawMode = 3: Used to draw Normal Vector Debug Visualization for mesh\n"
							"const int DRAW_BARYCENTRIC = 4; // DrawMode = 4: Used to draw mesh with each triangle filled using its barycenter RGB color\n"
							"const int DRAW_WIREFRAME   = 5; // DrawMode = 5: Used to draw mesh as wireframe\n"
							"const int DRAW_DIFFUSE     = 6; // DrawMode = 6: Used to draw Diffuse Lighting (Lambert)\n"
							"const int DRAW_PBR         = 7; // DrawMode = 7: Used to draw PBR Lighting\n"
							"\n"
							"void main()\n"
							"{\n"
							"    if(uDrawMode == DRAW_TEXTURE)\n"
							"    {\n"
							"        fragColor = texture(uTexture0, textureCoord);\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_FONT)\n"
							"    {\n"
							"        float alpha = texture(uTexture0, textureCoord.xy).x;\n"
							"        fragColor = vec4(uFontColor, alpha);\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_NORMALS)\n"
							"    {\n"
							"        vec3 n = normalize(vertexNormal.xyz);\n"
							"        fragColor = vec4(n * 0.5 + 0.5, 1.0);\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_BARYCENTRIC)\n"
							"    {\n"
							"        fragColor = vec4(barycentric, 1.0);\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_WIREFRAME)\n"
							"    {\n"
							"        float edge = min(min(barycentric.x, barycentric.y), barycentric.z);\n"
							"        float thickness = 0.001;        \n"
							"        if (edge < thickness)\n"
							"            fragColor = vec4(0.75, 0.75, 0.75, 1.0);\n"
							"        else\n"
							"            discard;\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_DIFFUSE)\n"
							"    {       \n"
							"        vec3 result = vec3(0.0);\n"
							"        \n"
							"        // Add Directional Lights\n"
							"        for (int i = 0; i < MAX_LIGHTS; ++i)\n"
							"        {\n"
							"            if (i >= uDirectionalLightCount) { break;}\n"
							"\n"
							"            vec3 N = normalize(vertexNormal);\n"
							"            vec3 L = normalize(-uDirectionalLightDirection[i]);\n"
							"\n"
							"            float NdotL = max(dot(N, L), 0.0);\n"
							"\n"
							"            vec3 diffuse = uAlbedo * uDirectionalLightColor[i] * uDirectionalLightIntensity[i] * NdotL;\n"
							"\n"
							"            result += diffuse;\n"
							"        }\n"
							"\n"
							"        // Add Point Lights\n"
							"        for (int i = 0; i < MAX_LIGHTS; ++i)\n"
							"        {\n"
							"            if (i >= uPointLightCount) { break;}\n"
							"            \n"
							"            vec3 N = normalize(vertexNormal);\n"
							"            vec3 lightDir = uPointLightPosition[i] - fragPosition;\n"
							"                        \n"
							"            float dist = length(lightDir);\n"
							"            lightDir = normalize(lightDir);\n"
							"            float NdotL = max(dot(N, lightDir), 0.0);\n"
							"            float attenuation = 0.8 / (dist * dist);\n"
							"            \n"
							"            vec3 diffuse =\n"
							"                uAlbedo *\n"
							"                uPointLightColor[i] *\n"
							"                uPointLightIntensity[i] *\n"
							"                NdotL *\n"
							"                attenuation;\n"
							"\n"
							"            result += diffuse;\n"
							"        }\n"
							"        \n"
							"        fragColor = vec4(result, 1.0);\n"
							"    }\n"
							"    else if(uDrawMode == DRAW_PBR)\n"
							"    {\n"
							"    }\n"
							"    else\n"
							"    {        \n"
							"        fragColor = color;\n"
							"    }\n"
							"}\n"
							"\n"
							"\n"
							"\n"
							;
						return fragmentShaderStr;
					}

				};
			}
		}
	}
}
#endif
