#ifndef __SPARK_RENDERER_SHADER_GLSL_FOR_SPIR_FEATURE_LEVEL_GLSLES10_HPP_INCLUDED__
#define __SPARK_RENDERER_SHADER_GLSL_FOR_SPIR_FEATURE_LEVEL_GLSLES10_HPP_INCLUDED__
#include <string>

namespace spark {
    namespace renderer {
        namespace shader {
            namespace glsl_for_spir_feature_level_glsles10 {
                /**
                * glslc.exe vertex.vert -o vertex.spv
                */
                class DefaultShader
                {
                public:
                    /**
                    *
                    */
                    const char* getVertexShader()
                    {
                        return m_base64VertexShader.c_str();
                    }

                    /**
                    *
                    */
                    const char* getFragmentShader()
                    {
                        return m_base64FragmentShader.c_str();
                    }

                private:
                    std::string m_base64VertexShader = "AwIjBwAAAQAKAAoANgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ACAAAAAAABAAAAG1haW4AAAAAIgAAACYAAAAxAAAAAwADAAIAAADvv70BAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAFAAwAAABwb3NpdGlvbnMAAAAFAAQAFwAAAGNvbG9ycwAABQAGACAAAABnbF9QZXJWZXJ0ZXgAAAAABgAGACAAAAAAAAAAZ2xfUG9zaXRpb24ABgAHACAAAAABAAAAZ2xfUG9pbnRTaXplAAAAAAYABwAgAAAAAgAAAGdsX0NsaXBEaXN0YW5jZQAGAAcAIAAAAAMAAABnbF9DdWxsRGlzdGFuY2UABQADACIAAAAAAAAABQAGACYAAABnbF9WZXJ0ZXhJbmRleAAABQAFADEAAABmcmFnQ29sb3IAAABIAAUAIAAAAAAAAAALAAAAAAAAAEgABQAgAAAAAQAAAAsAAAABAAAASAAFACAAAAACAAAACwAAAAMAAABIAAUAIAAAAAMAAAALAAAABAAAAEcAAwAgAAAAAgAAAEcABAAmAAAACwAAACoAAABHAAQAMQAAAB4AAAAAAAAAEwACAAIAAAAhAAMAAwAAAAIAAAAWAAMABgAAACAAAAAXAAQABwAAAAYAAAACAAAAFQAEAAgAAAAgAAAAAAAAACsABAAIAAAACQAAAAMAAAAcAAQACgAAAAcAAAAJAAAAIAAEAAsAAAAGAAAACgAAADsABAALAAAADAAAAAYAAAArAAQABgAAAAoAAAAAAAAAKwAEAAYAAAAOAAAAAAAA77+9LAAFAAcAAAAPAAAACgAAAA4AAAArAAQABgAAABAAAAAAAAA/LAAFAAcAAAARAAAAEAAAABAAAAAsAAUABwAAABIAAAAOAAAAEAAAACwABgAKAAAAEwAAAA8AAAARAAAAEgAAABcABAAUAAAABgAAAAMAAAAcAAQAFQAAABQAAAAJAAAAIAAEABYAAAAGAAAAFQAAADsABAAWAAAAFwAAAAYAAAArAAQABgAAABgAAAAAAO+/vT8sAAYAFAAAABkAAAAYAAAACgAAAAoAAAAsAAYAFAAAABoAAAAKAAAAGAAAAAoAAAAsAAYAFAAAABsAAAAKAAAACgAAABgAAAAsAAYAFQAAABwAAAAZAAAAGgAAABsAAAAXAAQAHQAAAAYAAAAEAAAAKwAEAAgAAAAeAAAAAQAAABwABAAfAAAABgAAAB4AAAAeAAYAIAAAAB0AAAAGAAAAHwAAAB8AAAAgAAQAIQAAAAMAAAAgAAAAOwAEACEAAAAiAAAAAwAAABUABAAjAAAAIAAAAAEAAAArAAQAIwAAACQAAAAAAAAAIAAEACUAAAABAAAAIwAAADsABAAlAAAAJgAAAAEAAAAgAAQAKAAAAAYAAAAHAAAAIAAEAC4AAAADAAAAHQAAACAABAAwAAAAAwAAABQAAAA7AAQAMAAAADEAAAADAAAAIAAEADMAAAAGAAAAFAAAADYABQACAAAABAAAAAAAAAADAAAA77+9AAIABQAAAD4AAwAMAAAAEwAAAD4AAwAXAAAAHAAAAD0ABAAjAAAAJwAAACYAAABBAAUAKAAAACkAAAAMAAAAJwAAAD0ABAAHAAAAKgAAACkAAABRAAUABgAAACsAAAAqAAAAAAAAAFEABQAGAAAALAAAACoAAAABAAAAUAAHAB0AAAAtAAAAKwAAACwAAAAKAAAAGAAAAEEABQAuAAAALwAAACIAAAAkAAAAPgADAC8AAAAtAAAAPQAEACMAAAAyAAAAJgAAAEEABQAzAAAANAAAABcAAAAyAAAAPQAEABQAAAA1AAAANAAAAD4AAwAxAAAANQAAAO+/vQABADgAAQA=";
                    std::string m_base64FragmentShader = "AwIjBwAAAQAKAAoAEwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAACQAAAAwAAAAQAAMABAAAAAcAAAADAAMAAgAAAO+/vQEAAAQACgBHTF9HT09HTEVfY3BwX3N0eWxlX2xpbmVfZGlyZWN0aXZlAAAEAAgAR0xfR09PR0xFX2luY2x1ZGVfZGlyZWN0aXZlAAUABAAEAAAAbWFpbgAAAAAFAAUACQAAAG91dENvbG9yAAAAAAUABQAMAAAAZnJhZ0NvbG9yAAAARwAEAAkAAAAeAAAAAAAAAEcABAAMAAAAHgAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAQAAAAgAAQACAAAAAMAAAAHAAAAOwAEAAgAAAAJAAAAAwAAABcABAAKAAAABgAAAAMAAAAgAAQACwAAAAEAAAAKAAAAOwAEAAsAAAAMAAAAAQAAACsABAAGAAAADgAAAAAA77+9PzYABQACAAAABAAAAAAAAAADAAAA77+9AAIABQAAAD0ABAAKAAAACgAAAAwAAABRAAUABgAAAA8AAAAKAAAAAAAAAFEABQAGAAAAEAAAAAoAAAABAAAAUQAFAAYAAAARAAAACgAAAAIAAABQAAcABwAAABIAAAAPAAAAEAAAABEAAAAOAAAAPgADAAkAAAASAAAA77+9AAEAOAABAA==";
                };
            }
        }
    }
}
#endif